#if !defined(AFX_GMAPX_H__1F10B957_C6E7_4696_A6FB_E56E7F06FBFB__INCLUDED_)
#define AFX_GMAPX_H__1F10B957_C6E7_4696_A6FB_E56E7F06FBFB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGmapx wrapper class

class CGmapx : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGmapx)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xad6cbf6, 0xe7e0, 0x466f, { 0x8a, 0xa3, 0x10, 0xe5, 0x9f, 0x2c, 0xba, 0xc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetMapURL(LPCTSTR mapurl);
	void SetMapLocPath(LPCTSTR mappath);
	void MapZoomIn();
	void MapZoomOut();
	long GetMapScale();
	void SetMapScale(long scale);
	void MoveMap(double longitude, double latitude);
	void ShowMap(double longitude, double latitude, long scale);
	long CreateICO(LPCTSTR path);
	BOOL CreateMapPoint(long pid, double longitude, double lanitude, LPCTSTR name, LPCTSTR text, long icoid);
	long SetMapPoint(long pid, double lonitude, double lanitude);
	long SetMapPointName(long pid, LPCTSTR name);
	long SetMapPointText(long pid, double longitude, double lanitude, LPCTSTR text);
	long SetMapPointICO(long pid, long icoid);
	long DeleteMapPoint(long pid);
	long CreateMapLine(long lid);
	long DeleteLine(long lid);
	long AddMapLinePoint(long lid, double longitude, double lanitude);
	long SetMapLineName(long lid, LPCTSTR name);
	long SetMapLineColor(long lid, long colorbgr);
	long SetMapLineWidth(long lid, long width);
	long CreateMapAround(long rid, double longitude, double lanitide, long radius, long alpha);
	long DeleteMapAround(long rid);
	long CreateMapText(long tid, double longitude, double lanitude, LPCTSTR text, long size, long colorbgr);
	long DeleteMapText(long tid);
	void Invalidate();
	void RemoveAllLayer();
	long SetMapTextFont(long size, long width, long escapement, long orientation, long weight, long Italic, long underline, long strikeOut, LPCTSTR fontname);
	BOOL IsInMapBound(double longitude, double lanigude);
	BOOL IsMapPointInMapCreen(double longitude, double lanitude);
	long CreateMapPolygon(long pid);
	long DeletePolygon(long pid);
	long AddMapPolygonPoint(long pid, double longitude, double lanitude);
	double GetMapCenterX();
	double GetMapCenterY();
	void MoveMapBound(double long1, double lan1, double long2, double lan2);
	long SetMapTools(long type);
	void ClearMapTools();
	long RegisterKey(LPCTSTR userkey);
	CString GetMapBound();
	CString GetMapOffSet(double lon, double lan);
	void SetMapLevelBount(long minlevel, long maxlevel);
	void SetMapScaleBound(long scalemin, long scalemax);
	long OpenAddMapLayer(LPCTSTR path);
	void CloseAddMapLayer();
	void DeleteAllMapPoint();
	BOOL IsInMapToolsPolygon(double lon, double lan);
	long SaveMapPoint(double lon, double lan, LPCTSTR name, LPCTSTR text, long icoid);
	long SaveMapLine(LPCTSTR name, LPCTSTR mappoints, long width, long colorbgr);
	long OpenMapEdit(long type, long id, BOOL bedit);
	long SetMapPolygonName(long pid, LPCTSTR name);
	long SetMapPolygonColor(long pid, long colorbgr);
	void SetMapAroundName(long rid, LPCTSTR name);
	long SetMapAroundColor(long rid, long colorbgr);
	void SetOnlineMap(long lMapType);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GMAPX_H__1F10B957_C6E7_4696_A6FB_E56E7F06FBFB__INCLUDED_)
